# Generated by Django 3.2.9 on 2021-12-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_alter_playlist_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='My Song', null=True)),
                ('artist', models.TextField(blank=True, default='My Artist', null=True)),
                ('link', models.TextField(blank=True, default='My link', null=True)),
                ('listenings', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
