# Generated by Django 3.2 on 2022-01-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='link',
        ),
        migrations.AddField(
            model_name='track',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
